### ISSUE TITLE
Decrease the latency of the weixin danmaku

### ISSUE THREAD

**Issue by AngelaYing** [aidistan/browser-weixin-danmu#3]
The previous conversation including the word sent by myself will be shown as the danmaku on the screen when a new message arrives.

**Comment by aidistan** [comment]
Got it. I will try to improve the user experience in following two ways:
- [ ] Filter out messages sent by current user
- [ ] Increase the size of the read message queue

**Comment by aidistan** [comment]
@AngelaYing Got it. I will try to improve the user experience in following two ways:
- [x] Filter out messages sent by current user
- [x] Increase the size of the read message queue
